name: Docker Pull Push Example

on:
  workflow_dispatch:

jobs:
  image_pull_push:
    name: Pull and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Pull Hello World
        run: |
          docker pull hello-world
          docker tag hello-world ghcr.io/${{ github.repository_owner }}/hello-world
      - name: Log in to GHE
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Hello World
        run: |
            docker push ghcr.io/${{ github.repository_owner }}/hello-world