name: Secret Test Workflow

on:
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      MY_SECRET_NAME:
        description: 'Name of the secret to test'
        required: false
        type: string
        default: "SECRET_TEST"

env:
  SECRET_TEST: ${{ secrets.SECRET_TEST }}
  SECRET_TEST_STRING: '{"key": "${{ secrets.SECRET_TEST }}"}'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run first job
        run: echo "SECRET_TEST_STRING=${{ env.SECRET_TEST_STRING }}"
  secret-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Run first job
        run: echo "SECRET_TEST_STRING=${{ secrets[inputs.MY_SECRET_NAME] }}"

